### PR TITLE
Returns status code on exception.

### PR DESCRIPTION
**Pull request by rossdeane**
Return the HTTP status code along with the message when a LinkedinAPIError exception is raised.

### CODE REVIEW

**Comment by michaelhelmick** [comment]
I'll take a look at this and merge it in over the weekend, thanks! :cake:

**Comment by michaelhelmick** [comment]
@rossdeane Finally got time to look over this, think you could make a change?

On Line #30 change:

``` python
class LinkedinAPIError(Exception): pass
```

to

``` python
class LinkedinAPIError(Exception):
    def __init__(self, message, code=None):
        self.message = message
        self.code = code

    def __str__(self):
        return repr(self.message)
```

Do that and I'll merge this in, thanks!

**Comment by rossdeane** [comment]
Done, thanks! :smile_cat:

**Comment by michaelhelmick** [comment]
`linkedin` 0.1.5 is now available via PyPi! Thanks! :cake:

**Pull request merged**
